set_property SRC_FILE_INFO {cfile:C:/share/my-systolic/syn/systolic_io_pins.xdc rfile:../../../../systolic_io_pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {rgb_led[2]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports {rgb_led[1]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {rgb_led[0]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clkin]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports rx]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports interrupt_0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports tx]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -min -add_delay 1.000 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -max -add_delay 1.000 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -min -add_delay 1.000 [get_ports rx]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -max -add_delay 1.000 [get_ports rx]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -min -add_delay 1.000 [get_ports interrupt_0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks  clk_out1_clk_wiz_0] -max -add_delay 1.000 [get_ports interrupt_0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_out1_clk_wiz_0] -min -add_delay -3.000 [get_ports {rgb_led[*]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_out1_clk_wiz_0] -max -add_delay -3.000 [get_ports {rgb_led[*]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_out1_clk_wiz_0] -min -add_delay -3.000 [get_ports tx]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_out1_clk_wiz_0] -max -add_delay -3.000 [get_ports tx]
